import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { useUser } from '@clerk/nextjs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [textInput, setTextInput] = useState('')

  const { isLoaded, isSignedIn, user } = useUser()
  console.log(user)

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='flex p-3 mt-5 font-normal justify-center text-lg h-96 xl:w-[60%] m-auto text-cyan-50 bg-slate-500 rounded-xl'>
          <form className='flex flex-col w-96'>
            <textarea className='p-2 bg-gray-900 rounded-md' onChange={e => setTextInput(e.target.value)} />
            <button className='' type='submit'>
              Submit
            </button>
          </form>
        </div>
      </main>
    </>
  )
}
